## Haiku Generic Makefile

## Application name
NAME = DocumentExporter

## Application type
TYPE = APP

## Sources
SRCS = DocumentExporter.cpp

## Required libraries 
LIBS = be translation stdc++

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = application/x-vnd.demo-docexporter

## Inclure le makefile système de Haiku
include $(BUILDHOME)/etc/makefile-engine
