## Haiku Generic Makefile

## Application name
NAME = LocaleTranslate

## Application type
TYPE = APP

## Sources
SRCS = LocaleTranslate.cpp

## Required libraries 
LIBS = be localestub stdc++

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Locales
LOCALES = en fr ja

## Application signature
APP_MIME_SIG = application/x-vnd-translateexample

## Include Haiku system makefile
include $(BUILDHOME)/etc/makefile-engine
