## Haiku Generic Makefile

## Application name
NAME = BufferEditor

## Application type
TYPE = APP

## Sources
SRCS = BufferEditor.cpp

## Required libraries 
LIBS = be tracker

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = application/x-vnd.example-BufferEditor

## Inclure le makefile système de Haiku
include $(BUILDHOME)/etc/makefile-engine
