## Haiku Generic Makefile

## Application name
NAME = ImageViewer

## Application type
TYPE = APP

## Sources
SRCS = ImageViewer.cpp

## Required libraries 
LIBS = be translation

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = application/x-vnd.demo-imageviewer

## Inclure le makefile système de Haiku
include $(BUILDHOME)/etc/makefile-engine
