## Haiku Generic Makefile

## Application name
NAME = ListHome

## Application type
TYPE = APP

## Sources
SRCS = ListHome.cpp

## Required libraries 
LIBS = be

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = application/x-vnd.kitlab-listhome

## Include system makefile from Haiku
include $(BUILDHOME)/etc/makefile-engine
