## Haiku Generic Makefile

## Application name
NAME = InputApp

## Application type
TYPE = APP

## Sources
SRCS = InputApp.cpp

## Required libraries 
LIBS = be

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = application/x-vnd.example-input

## Inclure le makefile système de Haiku
include $(BUILDHOME)/etc/makefile-engine
