## Haiku Generic Makefile

## Application name
NAME = MessageApp

## Application type
TYPE = APP

## Sources
SRCS = MessageApp.cpp

## Required libraries 
LIBS = be

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = application/x-vnd.example-bmessenger

## Include Haiku engine makefile 
include $(BUILDHOME)/etc/makefile-engine
