## Haiku Generic Makefile

## Application name
NAME = Interaction

## Application type
TYPE = APP

## Sources
SRCS = Interaction.cpp

## Required libraries 
LIBS = be stdc++

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = application/x-vnd.example-systemkit

## Include Haiku engine makefile 
include $(BUILDHOME)/etc/makefile-engine
