## Haiku Generic Makefile

## Application name
NAME = LocaleDemo

## Application type
TYPE = APP

## Sources
SRCS = LocaleDemo.cpp

## Required libraries 
LIBS = be localestub stdc++

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = application/x-vnd-localeexample

## Include Haiku system makefile
include $(BUILDHOME)/etc/makefile-engine
