## Haiku Generic Makefile

## Application name
NAME = NodeAttributes

## Application type
TYPE = APP

## Sources
SRCS = NodeAttributes.cpp

## Required libraries 
LIBS = be

## Headers location 
# SYSTEM_INCLUDE_PATHS = 

## Ressources (icons, etc.)
# RSRCS = 

## Application signature
APP_MIME_SIG = x-vnd.kitlab-nodeattributes

## Include system makefile from Haiku
include $(BUILDHOME)/etc/makefile-engine
